import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Geist, Geist_Mono } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { Suspense } from 'react';

import { AppHeader } from '@/components/AppHeader';
import { WithApplicationCleanup } from '@/components/WithApplicationCleanup';
import { featureService, i18nService } from '@/index';


import { ThemeProvider } from '../shadcn/components/ThemeProvider';

import type { Metadata } from 'next';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
}) {
  const params = await props.params;
  const { children } = props;
  const { locale } = params;
  const messages = await i18nService.getMessages(locale);
  const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const analyticsFeature = featureService.getFeature('analytics');
  const speedInsightsFeature = featureService.getFeature('speedInsights');
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider
          timeZone={timeZone}
          locale={locale}
          messages={messages as IntlMessages}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <Suspense fallback={<div>Loading...</div>}>
              <WithApplicationCleanup>
                <div className="min-h-screen">
                  <AppHeader />
                  {children}
                </div>
              </WithApplicationCleanup>
            </Suspense>
          </ThemeProvider>
        </NextIntlClientProvider>
        {analyticsFeature.enabled && <Analytics />}
        {speedInsightsFeature.enabled && <SpeedInsights />}
      </body>
    </html>
  );
}
