import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Suspense } from 'react';

import { WithApplicationCleanup } from '@/components/WithApplicationCleanup';
import { featureService } from '@/index';
import { AppHeader } from '@/shadcn/components/AppHeader';


import type { Metadata } from 'next';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const analyticsFeature = featureService.getFeature('analytics');
  const speedInsightsFeature = featureService.getFeature('speedInsights');
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<div>Loading...</div>}>
          <WithApplicationCleanup>
            <div className="min-h-screen">
              <AppHeader />
              {children}</div>
          </WithApplicationCleanup>
        </Suspense>
        {analyticsFeature.enabled && <Analytics />}
        {speedInsightsFeature.enabled && <SpeedInsights />}
      </body>
    </html>
  );
}
