/**
 * build-workers.ts
 * ---------------------------------------------
 * Purpose:
 *   Builds each Web Worker located under `src/workers/<WorkerName>/index.ts`
 *   into an individual bundled JavaScript file placed in `public/workers`.
 *
 * Rationale:
 *   Next.js does not (yet) provide a first-class abstraction for authoring and
 *   bundling multiple custom Web Workers. This script centralizes that build
 *   process using `esbuild` for speed and simplicity, producing self‑contained
 *   IIFE bundles suitable for direct use via `new Worker('/workers/<name>.js')`.
 *
 * CLI Usage Examples:
 *   node ./src/tools/build-workers.js --minimize --sourcemap
 *   node ./src/tools/build-workers.js -m -s
 *   node ./src/tools/build-workers.js --help
 *
 * Flags:
 *   -m, --minimize   Enable JS minification (recommended for production)
 *   -s, --sourcemap  Emit source maps alongside bundles
 *   -h, --help       Show autogenerated help and exit
 *
 * Output:
 *   For each directory inside `src/workers` (e.g. `LoggerWorker`) an output
 *   file `public/workers/LoggerWorker.js` (and optional .js.map) is generated.
 *
 * Notes:
 *   - Bundles are built in parallel with Promise.all for speed.
 *   - The build target is modern (ES2022) since workers run in evergreen engines.
 *   - The format is set to `iife` so the worker scope is clean and immediately executed.
 *   - `process.env.NODE_ENV` is defined as "production" to aid dead‑code elimination.
 *
 * Exit Codes:
 *   0: Success / help displayed
 *   1: Argument parsing failure or build failure
 *
 * This file intentionally limits its responsibilities to discovery + build;
 * any future concerns (e.g. type generation, hash naming, watch mode) should
 * be added as separate, clearly delineated steps.
 */

import { Console } from 'console';
import fs from 'fs';
import path from 'path';

import esbuild from 'esbuild';
import { parse } from 'ts-command-line-args';

/**
 * Parsed command line options.
 *
 * All boolean flags default to `false` when not supplied unless the parser
 * changes its defaults. The `help` field, when present & true, short‑circuits
 * execution after printing help text (handled internally by the parser).
 */
interface CommandLineOptions {
  /** Minify output bundles (alias: -m) */
  minimize: boolean;
  /** Emit source maps beside each worker bundle (alias: -s) */
  sourcemap: boolean;
  /** Trigger help output (alias: -h) */
  help?: boolean;
}

const console = new Console({
  stdout: process.stdout,
  stderr: process.stderr,
});

/**
 * Orchestrates argument parsing, worker discovery, and parallel builds.
 *
 * Steps:
 *   1. Parse & validate CLI arguments.
 *   2. Discover subdirectories of `src/workers` as worker names.
 *   3. For each worker, construct entry/output paths.
 *   4. Build all workers in parallel via esbuild.
 */
async function main() {
  const argsDefinitions = {
    minimize: { type: Boolean, alias: 'm', description: 'Minimize the output' },
    sourcemap: { type: Boolean, alias: 's', description: 'Generate sourcemaps' },
    help: { type: Boolean, alias: 'h', description: 'Display this help message', optional: true },
  } as const;

  let options: CommandLineOptions;
  try {
    // parse command line arguments
    options = parse<CommandLineOptions>(argsDefinitions, {
      stopAtFirstUnknown: true,
      partial: true,
      helpArg: 'help',
    });
    if (options.help) {
      process.exit(0);
    }
  } catch (error) {
    console.error('Error parsing command line arguments:', error);
    process.exit(1);
  }

  // Absolute paths for input (individual worker directories) and output bundles.
  const srcWorkersDir = path.join(__dirname, '../workers');
  const outputDir = path.join(__dirname, '../../public/workers');

  // Ensure output directory exists (idempotent). This is purely defensive.
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Find all worker entry points
  const workerDirs = fs.readdirSync(srcWorkersDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

  if (workerDirs.length === 0) {
    console.warn('No worker directories found. Nothing to build.');
    return;
  }

  // Build each worker as a separate bundle
  try {
    await Promise.all(
      workerDirs.map(workerName => {
        const entryPoint = path.join(srcWorkersDir, workerName, 'index.ts');
        const outfile = path.join(outputDir, `${workerName}.js`);

        // Each worker becomes a self‑contained bundle. Additional per‑worker
        // customization could be added here in the future (e.g. env defines).
        return esbuild.build({
          entryPoints: [entryPoint],
          bundle: true,
          outfile: outfile,
          format: 'iife', // Immediately Invoked Function Expression for web workers
          target: 'es2022',
          minify: options.minimize, // Set to true for production
          sourcemap: options.sourcemap,
          platform: 'browser',
          define: {
            'process.env.NODE_ENV': '"production"',
          },
        });
      }),
    );
    console.log('Workers built successfully!');
  } catch (error) {
    console.error('Build failed:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

// Execute the main function
main().catch((error) => {
  console.error('Unhandled error:', error);
  process.exit(1);
});
